---
title: "CV"
---

## Education
<b>University of Minnesota, Twin Cities [Fall 2019 – Current] </b>
<br>&emsp;&emsp;Educational Psychology MA & PhD Program </br>
&emsp;&emsp;Psychological Foundations Social Track

   
<b>College of Saint Benedict/Saint John’s University [Fall 2012 – Spring 2016] </b>
<br>&emsp;&emsp;Psychology Major, German Minor </br>
&emsp;&emsp;Distinction in Psychology, BA Obtained

<b>Saint John’s Preparatory High School [Fall 2007 – Spring 2012] </b>

## Teaching Experience

<b>UMN Student Learning & Social Psychology of Education Teaching Assistant [Fall 2021 – Current] </b>
<p style="margin-left: 50px;">Assisting in the creation and revamping of course materials through implementation of new learning techniques, grading assignments, reviewing discussion posts, taking attendance, and aiding students in their studying and understanding of challenging course concepts </p>


<b>UMN Psychological Science Applied Teaching Assistant [Fall 2019 – Spring 2021] </b>
<p style="margin-left: 50px;">Teaching lab sections to apply the concepts learned in lecture, helping to create and revamp course material through implementation of new learning technologies, grading assignments, and aiding students in their studying and understanding of the more challenging course concepts </p>